# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-JSON' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReachabilitySwift'
  pod 'SwiftMessages'
  pod 'NVActivityIndicatorView'

end
